"""empty message

Revision ID: e6aac02037d7
Revises: 
Create Date: 2024-05-16 18:46:21.561809

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e6aac02037d7'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('url_mapping',
    sa.Column('shorten_key', sa.String(), nullable=False),
    sa.Column('original_url', sa.String(), nullable=False),
    sa.Column('expire_date', sa.DateTime(), nullable=True),
    sa.Column('views', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('shorten_key')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('url_mapping')
    # ### end Alembic commands ###
